### PR TITLE
Bugfix: mobile view along with Nucleus

### PR DESCRIPTION
**Pull request by ssahabg**
**Description**

`easy-slot-picker` does not render properly in mobile due to CSS override by Nucleus styles.

**Issue**

The following Nucleus styles (padding-left and max-width) override the horizontal-list-swiper/gesture2 component styles

image

### CODE REVIEW

**Comment by Leooo** [comment]
thanks @ssahabg . Not quite sure why the tests are failing atm tho

**Comment by ssahabg** [comment]
> thanks @ssahabg . Not quite sure why the tests are failing atm tho

Hi @Leooo - It fails here https://travis-ci.com/github/britishgas-engineering/ember-appointment-slots-pickers/jobs/355800814. Will try to debug in local.

**Comment by Leooo** [comment]
@ssahabg must be https://github.com/gruntjs/grunt-contrib-uglify/issues/406#issuecomment-642197477

**Comment by Leooo** [comment]
currently using "ember-cli-moment-shim": {
      "version": "3.7.1",

need to update to 3.8.0

in https://github.com/britishgas-engineering/ember-appointment-slots-pickers/blob/bugfix/mobile-view-with-nucleus/package.json#L42

**Comment by ssahabg** [comment]
> currently using "ember-cli-moment-shim": {
> "version": "3.7.1",
> 
> need to update to 3.8.0
> 
> in https://github.com/britishgas-engineering/ember-appointment-slots-pickers/blob/bugfix/mobile-view-with-nucleus/package.json#L42

Thanks @Leooo - Build is passing now.

**Review by Leooo — APPROVED** [review]

**Pull request merged**
